SGeBank/Controllers/ClientsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using eMais.ApplicationMgr;
using SGeBank.Models.BasicMgr;
using SGeBank.Models.BasicMgr.Bean;
using SGeBank.Models.ClientMgr;
using SGeBank.Models.ClientMgr.Bean;
using SGeBank.Models.ClientMgr.Db;

namespace SGeBank.Controllers
{
    [Authorize]
    public class ClientsController : Controller
    {
        private ClientMgrDbContext db = new ClientMgrDbContext();

        // GET: Clients
        public ActionResult Index()
        {
            //return View(db.Clients.ToList());
            return View(db.vwClients.ToList());
        }

        // GET: Clients/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = db.Clients.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        // GET: Clients/Create
        public ActionResult Create()
        {
            List<GeneralClassifier> DocType = BasicManager.GetAllGNClassifierByType("DOCTYPE_CLASSIFIER").ToList();
            List<GeneralClassifier> Gender = BasicManager.GetAllGNClassifierByType("GENDER_CLASSIFIER").ToList();
            ViewData["DOCTYPE"] = DocType;
            ViewData["GENDER"] = Gender;
            return PartialView();
        }

        // POST: Clients/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "cid,clientName,clientSurname,cDoctype,cDocnum,cGender,cAddress,cPhone,cPhone2,cEmail")] Client client)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var c = ClientManager.Create(client);
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    string innerExp = "";
                    if (ex.InnerException != null)
                    {
                        innerExp = "controller [eBank.Controllers.CientsController] " +
                        " action [ConfigureUser] error: " + ex.InnerException;
                    }

                    LogsManager.writeErrorLogs(ex.Message, innerExp);
                }
            }
            
            return View(client);
        }

        // GET: Clients/Edit/5
        public ActionResult Edit(string id)
        {
            if (string.IsNullOrWhiteSpace(id))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = db.Clients.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            List<GeneralClassifier> DocType = BasicManager.GetAllGNClassifierByType("DOCTYPE_CLASSIFIER").ToList();
            List<GeneralClassifier> Gender = BasicManager.GetAllGNClassifierByType("GENDER_CLASSIFIER").ToList();
            ViewData["DOCTYPE"] = DocType;
            ViewData["GENDER"] = Gender;
            return View(client);
        }

        // POST: Clients/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "cid,clientName,clientSurname,cDoctype,cDocnum,cGender,cAddress,cPhone,cPhone2,cEmail")] Client client)
        {
            if (ModelState.IsValid)
            {
                db.Entry(client).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(client);
        }

        // GET: Clients/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = db.Clients.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        // POST: Clients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Client client = db.Clients.Find(id);
            db.Clients.Remove(client);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SGeBank/Controllers/LoansController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SGeBank.Models.ClientMgr;
using SGeBank.Models.ClientMgr.Bean;
using SGeBank.Models.LoanMgr;
using SGeBank.Models.LoanMgr.Bean;
using SGeBank.Models.LoanMgr.Db;
using SGeBank.Models.WorkerMgr;
using SGeBank.Models.WorkerMgr.Bean;

namespace SGeBank.Controllers
{
    public class LoansController : Controller
    {
        private LoanMgrDbContext db = new LoanMgrDbContext();

        // GET: Loans
        public ActionResult Index()
        {
            //return View(db.loans.ToList());
            return View(db.vwLoans.ToList());
        }

        // GET: Loans/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Loan loan = db.loans.Find(id);
            if (loan == null)
            {
                return HttpNotFound();
            }
            return View(loan);
        }

        // GET: Loans/Create
        public ActionResult Create()
        {
            List<SelectListItem> paymentType = new List<SelectListItem>
            {
                new SelectListItem() { Text = "Semanal", Selected = true, Value = "7"},
                new SelectListItem() { Text = "Quinzenal", Selected = false, Value = "15"},
                new SelectListItem() { Text = "Mensal", Selected = false, Value = "30"},
            };

            List<SelectListItem> paymentTax = new List<SelectListItem>
            {
                new SelectListItem() { Text = "25%", Selected = true, Value = "25"},
                new SelectListItem() { Text = "30%", Selected = false, Value = "30"},
                new SelectListItem() { Text = "40%", Selected = false, Value = "40"},
                new SelectListItem() { Text = "45%", Selected = false, Value = "45"},
            };
            List<vwWorkers> Workers = WorkerManager.GetAllWorkersByType("GESTOR").ToList();
            List<vwClients> Clients = ClientManager.GetAllClients();
            ViewData["WORKERS"] = Workers;
            ViewData["CLIENTS"] = Clients;
            ViewData["PAYMENT_TYPE"] = paymentType;
            ViewData["PAYMENT_TAX"] = paymentTax;
            return View();
        }

        // POST: Loans/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "lID,clientId,workerId,loanValue,lparcelType,lparcelNum,lTax,lPaymentValue,lParcelValue,lIncome,lDate,lBalance,lExpiredDate,lPaymentDate")] Loan loan)
        {
            if (ModelState.IsValid)
            {
                loan.lPaymentValue = Convert.ToDecimal(Request.Form["payment"]);
                loan.lParcelValue = Convert.ToDecimal(Request.Form["parcel"]);
                loan.lIncome = Convert.ToDecimal(Request.Form["income"]);
                LoanManager.Create(loan);
                //db.loans.Add(loan);
                //db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(loan);
        }

        // GET: Loans/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Loan loan = db.loans.Find(id);
            if (loan == null)
            {
                return HttpNotFound();
            }
            return View(loan);
        }

        // POST: Loans/Edit/5
        // To protect from overposting attacks, enable       the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "lID,clientId,workerId,loanValue,lparcelType,lparcelNum,lTax,lPaymentValue,lParcelValue,lIncome,lDate,lBalance,lExpiredDate,lPaymentDate")] Loan loan)
        {
            if (ModelState.IsValid)
            {
                db.Entry(loan).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(loan);
        }

        // GET: Loans/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Loan loan = db.loans.Find(id);
            if (loan == null)
            {
                return HttpNotFound();
            }
            return View(loan);
        }

        // POST: Loans/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Loan loan = db.loans.Find(id);
            db.loans.Remove(loan);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        #region PARCELS
        public ActionResult GetParcelByLoanId(string loanId)
        {
            List<vwParcel> model = new List<vwParcel>();
            model = LoanManager.getParcelsByLoanId(loanId);
            return View("~/Views/Loans/Parcels/Parcels.cshtml", model);
        }
        public ActionResult ParcelPayment(string[] order)
        {
            return View("");
        }
        #endregion
    }
}

SGeBank/Controllers/WorkersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SGeBank.Models.BasicMgr;
using SGeBank.Models.BasicMgr.Bean;
using SGeBank.Models.WorkerMgr;
using SGeBank.Models.WorkerMgr.Bean;
using SGeBank.Models.WorkerMgr.Db;

namespace SGeBank.Controllers
{
    public class WorkersController : Controller
    {
        private WorkerMgrDbContext db = new WorkerMgrDbContext();

        // GET: Workers
        public ActionResult Index()
        {
            //return View(db.workers.ToList());
            return View(db.vwWorkers.ToList());
        }

        // GET: Workers/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Worker worker = db.workers.Find(id);
            if (worker == null)
            {
                return HttpNotFound();
            }
            return View(worker);
        }

        // GET: Workers/Create
        public ActionResult Create()
        {
            List<GeneralClassifier> DocType = BasicManager.GetAllGNClassifierByType("DOCTYPE_CLASSIFIER").ToList();
            List<GeneralClassifier> Gender = BasicManager.GetAllGNClassifierByType("GENDER_CLASSIFIER").ToList();
            List<GeneralClassifier> WType = BasicManager.GetAllGNClassifierByType("WORKER_TYPE").ToList();
            ViewData["DOCTYPE"] = DocType;
            ViewData["GENDER"] = Gender;
            ViewData["WTYPE"] = WType;
            return View();
        }

        // POST: Workers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "wid,workerName,workerSurname,wDoctype,wType,cDocnum,wGender,wAddress,wPhone,wPhone2,wEmail")] Worker worker)
        {
            if (ModelState.IsValid)
            {
                var c = WorkerManager.Create(worker);
                //db.workers.Add(worker);
                //db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(worker);
        }

        // GET: Workers/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Worker worker = db.workers.Find(id);
            if (worker == null)
            {
                return HttpNotFound();
            }
            List<GeneralClassifier> DocType = BasicManager.GetAllGNClassifierByType("DOCTYPE_CLASSIFIER").ToList();
            List<GeneralClassifier> Gender = BasicManager.GetAllGNClassifierByType("GENDER_CLASSIFIER").ToList();
            List<GeneralClassifier> WType = BasicManager.GetAllGNClassifierByType("WORKER_TYPE").ToList();
            ViewData["DOCTYPE"] = DocType;
            ViewData["GENDER"] = Gender;
            ViewData["WTYPE"] = WType;
            return View(worker);
        }

        // POST: Workers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "wid,workerName,workerSurname,wDoctype,wType,cDocnum,wGender,wAddress,wPhone,wPhone2,wEmail")] Worker worker)
        {
            if (ModelState.IsValid)
            {
                db.Entry(worker).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(worker);
        }

        // GET: Workers/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Worker worker = db.workers.Find(id);
            if (worker == null)
            {
                return HttpNotFound();
            }
            return View(worker);
        }

        // POST: Workers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Worker worker = db.workers.Find(id);
            db.workers.Remove(worker);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SGeBank/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Static Navigation - SB Admin</title>

    <script src="~/Scripts/jquery-3.5.1.js"></script>

    @*<link href="css/styles.css" rel="stylesheet" />*@
    <link href="~/Content/startbootstrap/dist/css/styles.css" rel="stylesheet" />

    @*<link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet" crossorigin="anonymous" />*@
    <link href="~/Content/startbootstrap/dist/css/dataTables.bootstrap4.min.css" rel="stylesheet" />

    @*<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js" crossorigin="anonymous"></script>*@
    <script src="~/Content/startbootstrap/dist/js/all.min.js"></script>

    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

    <!--  Unobtrusive Ajax Plugin    -->
    <script src="~/Content/assets/js/plugins/jquery.unobtrusive-ajax.min.js"></script>
    @*@Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")*@
</head>
<body>
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <!-- Navbar Brand-->
        <a class="navbar-brand ps-3" href="index.html">eBank</a>
        <!-- Sidebar Toggle-->
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        @Html.Partial("_LoginPartial")
        <!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
            <div class="input-group">
                <input class="form-control" type="text" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2" />
                <div class="input-group-append">
                    <button class="btn btn-primary" type="button"><i class="fas fa-search"></i></button>
                </div>
            </div>
        </form>
        <!-- Navbar-->
        <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="#!">Settings</a></li>
                    <li><a class="dropdown-item" href="#!">Activity Log</a></li>
                    <li><hr class="dropdown-divider" /></li>
                    <li><a class="dropdown-item" href="#!">Logout</a></li>
                </ul>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Core</div>
                        <a class="nav-link" href="@Url.Action("Index","Home")">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Pagina inicial
                        </a>
                        <div class="sb-sidenav-menu-heading">Configuracaoes</div>
                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                            <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                            Parametricacao
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" href="layout-static.html">Static Navigation</a>
                                <a class="nav-link" href="layout-sidenav-light.html">Light Sidenav</a>
                            </nav>
                        </div>
                        @*<a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
                                <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                                Pages
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                            </a>
                            <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-bs-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                                    <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseAuth" aria-expanded="false" aria-controls="pagesCollapseAuth">
                                        Authentication
                                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                    </a>
                                    <div class="collapse" id="pagesCollapseAuth" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                                        <nav class="sb-sidenav-menu-nested nav">
                                            <a class="nav-link" href="login.html">Login</a>
                                            <a class="nav-link" href="register.html">Register</a>
                                            <a class="nav-link" href="password.html">Forgot Password</a>
                                        </nav>
                                    </div>
                                    <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseError" aria-expanded="false" aria-controls="pagesCollapseError">
                                        Error
                                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                    </a>
                                    <div class="collapse" id="pagesCollapseError" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                                        <nav class="sb-sidenav-menu-nested nav">
                                            <a class="nav-link" href="401.html">401 Page</a>
                                            <a class="nav-link" href="404.html">404 Page</a>
                                            <a class="nav-link" href="500.html">500 Page</a>
                                        </nav>
                                    </div>
                                </nav>
                            </div>*@
                        <div class="sb-sidenav-menu-heading">Funcionalidades</div>
                        <a class="nav-link" href="charts.html">
                            <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                            Graficos
                        </a>
                        <a class="nav-link" href="@Url.Action("Index", "Clients")">
                            <div class="sb-nav-link-icon"><i class="fas fa-user"></i></div>
                            Clientes
                        </a>
                        <a class="nav-link" href="@Url.Action("Index", "Workers")">
                            <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                            Funcionarios
                        </a>
                        <a class="nav-link" href="@Url.Action("Index", "Loans")">
                            <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                            Emprestimos
                        </a>
                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Logged in as:</div>
                    @if (Request.IsAuthenticated)
                    {
                        @User.Identity.GetUserName()
                    }

                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid px-4">
                    @RenderBody()
                </div>
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Your Website 2022</div>
                        <div>
                            @*<a href="#">Privacy Policy</a>
                                &middot;
                                <a href="#">Terms &amp; Conditions</a>*@
                            <p>&copy; @DateTime.Now.Year eBank - Sistema de Gestao de Emprestimos Bancarios</p>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>


    @*<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>*@
    <script src="~/Scripts/jquery-3.5.1.slim.min.js"></script>

    @*<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>*@
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>

    @*<script src="js/scripts.js"></script>*@
    <script src="~/Content/startbootstrap/dist/js/scripts.js"></script>

    @*<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>*@
    @*<script src="assets/demo/chart-area-demo.js"></script>*@
    @*<script src="assets/demo/chart-bar-demo.js"></script>*@

    @*<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>*@
    <script src="~/Content/startbootstrap/dist/js/jquery.dataTables.min.js"></script>

    @*<script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>*@
    <script src="~/Content/startbootstrap/dist/js/dataTables.bootstrap4.min.js"></script>
    @*<script src="assets/demo/datatables-demo.js"></script>*@


    @*@Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)*@
</body>
</html>